### ISSUE TITLE
Remove width and height attributes from images

### ISSUE THREAD

**Issue by cillianderoiste** [ploneintranet/ploneintranet#83]
Image dimensions should be set by CSS alone.

**Comment by pbauer** [comment]
For the type images that is already done in https://github.com/ploneintranet/ploneintranet/commit/9dd7ee97feed72b5581324f7f1a8ba2351ad692c. Should we do this for all images (e.g. images added using the richtext-editor)? If yes, that could be fixed in plone-core.

**Comment by gyst** [comment]
Let's constrain this to the ploneintranet scope. +1 for replacing all hardcoded ploneintranet image tags with css specs. @cornae do you agree?

**Comment by cornae** [comment]
Image dimensions should not be set by CSS, but they are constrained by CSS with a max-width property. Since websites typically fluid/responsive, we no longer use width/height attributes on image tags. The content editor in Plone still does that. 

I disagree that the priority of this is set to low. Without this fix, many images with look horribly malformed when the pages are rendered, especially larger images on smaller screens will be squeezed and pulled out of proportion. 

To the scope: To me it's the same if it's fixed in PI only or in Plone all together, but I would guess that it would be beneficial for Plone too to have it changed there.

**Comment by gyst** [comment]
Removed prio:low. Since we'll ship with Raptor we need to ensure that both our templates AND Raptor emit clean img tags without width/height attrs. Whatever contenteditor the rest of Plone uses does not impact us for this project.

**Comment by cornae** [comment]
You’re right. Besides what the editor puts, there’s also the dimensions of which attributes get cleaned by Plone upon save. Isn’t that a simple setting on the Plone setting page?

**Comment by pilz** [comment]
Can somebody say where this still happens? We removed them in the library and news tile on dashboard and pat-raptor doesn't even have an image picker yet, so we may not have an issue.

**Comment by cornae** [comment]
True. But I saw it when @pbauer demonstrated a content page. How did we get an image in the first place?

**Comment by pilz** [comment]
Show me where and I tell you :) Perhaps it was an image object?

**Comment by cornae** [comment]
It was an image in inline rich content.

**Comment by pilz** [comment]
That is currently not possible to add. So we simply need to take into consideration that when we implement an image picker, it mustn't add dimension attributes.

**Comment by cornae** [comment]
I got that ;)

**Comment by gyst** [comment]
On 10/07/15 12:48, Alexander Pilz wrote:

> That is currently not possible to add. So we simply need to take into

Actually it is, in the library, via Barceloneta with TinyMCE.

> consideration that when we implement an image picker, it mustn't add
> dimension attributes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ploneintranet/ploneintranet/issues/83#issuecomment-120380856.

## 

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by pilz** [comment]
brrr, it haunts me.

**Comment by cornae** [comment]
@gyst True!!
